[build]
  # Folder tempat hasil build disimpan
  publish = "dist"
  command = "npm run build" # Perintah untuk build proyek (pastikan sudah sesuai dengan proyek Anda)

[[redirects]]
  # Redirect untuk root ke index.html
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # Redirect untuk /about ke about.html
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  # Redirect untuk /license ke license.html
  from = "/license"
  to = "/license.html"
  status = 200
