[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/license"
to = "/license.html"
status = 200

[[redirects]]
from = "/about"
to = "/about.html"
status = 200
